RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, only: [:new, :create, :index, :show, :edit, :update]

  resources :posts, only: [:new, :create, :show, :edit, :update]

  post '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote'
  post '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote'

end

RedditOnRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditOnRails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  content    :text             not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  vote_tally :integer          default(0), not null
#  url        :string
#

class Post < ApplicationRecord

  validates :title, :content, :author_id, presence: true

  has_many :sp_interfaces,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :SpInterface,
    inverse_of: :post

  has_many :subs,
    through: :sp_interfaces,
    source: :sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :votes,
    as: :votable

end

RedditOnRails/app/models/sp_interface.rb
# == Schema Information
#
# Table name: sp_interfaces
#
#  id         :bigint(8)        not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SpInterface < ApplicationRecord

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post


end

RedditOnRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  description  :text             not null
#  moderator_id :integer          not null
#

class Sub < ApplicationRecord

  validates :title, :description, uniqueness: true, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :sp_interfaces,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :SpInterface

  has_many :posts,
    through: :sp_interfaces,
    source: :post

end

RedditOnRails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil:true}

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :subs_moderated,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post


  def self.find_by_credentials(username, pw)
    @user = User.find_by(username: username)
    if @user && is_password?(pw)
      return @user
    else
      nil
    end
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

RedditOnRails/app/models/vote.rb
class Vote < ApplicationRecord

  validates :value, presence: true

  belongs_to :votable, polymorphic: true

  
end

RedditOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
    redirect_to subs_url
  end

  def sign_out
    current_user.reset_session_token
    current_user.session_token = nil
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end

end

RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @subs = Sub.all
    # @post = Post.new(post_params)
    @post = current_user.posts.new(post_params)
    @post.author_id = current_user.id

    # sub_ids = params[:post][:sub_ids][1..-1]
    # # sub_ids = post_params[:sub_ids][1..-1]
    # sub_ids.map! {|id| id.to_i}

    if @post.save
      # unless sub_ids.empty?
        # sub_ids.each do |sub_id|
        #   SpInterface.new(sub_id: sub_id, post_id: @post.id)
        # end
      # end

      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @subs = Sub.all
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.vote_tally += 1
    @post.save
    redirect_to post_url(@post)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.vote_tally -= 1
    @post.save
    redirect_to post_url(@post)
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :url, :sub_ids => [])
  end

end

RedditOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      sign_in(@user)
    else
      flash[:errors] = "Invalid login creds"
      render :new
    end
  end

  def destroy
    sign_out
  end

end

RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController



  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

RedditOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditOnRails/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

RedditOnRails/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditOnRails/app/helpers/sub_helper.rb
module SubHelper
end

RedditOnRails/app/helpers/subs_helper.rb
module SubsHelper
end

RedditOnRails/app/helpers/users_helper.rb
module UsersHelper
end

RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RedditOnRails/app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<form action="<%= post_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %> ">
  </label><br>

  <label>Content:
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label><br>

  <label>URL:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label><br><br>

  <!-- Subs -->
  <input type="hidden" name="post[sub_ids][]">
    <% @subs.each do |sub| %>
      <label>
        <input type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>">
        <%= sub.title %>
      </label><br>
  <% end %>

  <input type="submit" value="Edit Post">

</form>

RedditOnRails/app/views/posts/new.html.erb
<h3>New Post</h3>

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label><br>

  <label>Content:
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label><br>

  <label>URL:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label><br><br>

  <!-- Subs -->
  <input type="hidden" name="post[sub_ids][]">
    <% @subs.each do |sub| %>
      <label>
        <input type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>">
        <%= sub.title %>
      </label><br>
  <% end %>

  <input type="submit" value="Create Post">

</form>

RedditOnRails/app/views/posts/show.html.erb
<%= @post.title %>
<br>
<br>
<%= @post.content %><br>

<a href="<%=edit_post_url%>">Edit Post</a>

<br>Tally:
<%= @post.vote_tally %>
<br>

<form action=" <%= upvote_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="Upvote">
</form>

<form action=" <%= downvote_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="Downvote">
</form>
<br><br><br>
Comments
<!--  -->

RedditOnRails/app/views/subs/index.html.erb
<h2>Subs Index Page</h2>

  <ul>
    <% @subs.each do |sub| %>
      <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
  </ul>

RedditOnRails/app/views/subs/new.html.erb
 <h2>Create New Sub</h2>

 <form action="<%= subs_url %>" method="post">
   <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

   <label>Sub Title:
     <input type="text" name="sub[title]" value="<%= @sub.title %>">
   </label>

   <label>Sub Description:
     <input type="text" name="sub[description]" value="<%= @sub.description %>">
   </label>

   <input type="submit" name="" value="Create Sub!">
 </form>

RedditOnRails/app/views/subs/show.html.erb
<h3>Sub: <%= @sub.title %></h3>
<p> <%= @sub.description %> </p>

<% @sub.posts.each do |post| %>
<ul>
  <li>  <a href="<%= post_url(post) %>"><%= post.title %></a> </li>

  <br>Tally:
  <%= post.vote_tally %>
  <br>

  <form action=" <%= upvote_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" name="" value="Upvote">
  </form>

  <form action=" <%= downvote_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" name="" value="Downvote">
  </form>
</ul>
<% end %>

RedditOnRails/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>

  <input type="submit" value="Sign Up!">

</form>